name: Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Remote Server
              uses: appleboy/ssh-action@v1.2.2
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                script: |
                    cd EXE_BE
                    git pull
                    dotnet ef database update
                    dotnet publish -c Release -o out
                    sudo systemctl restart exe.service
                    systemctl status exe.service
