name: Deploy

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Remote Server
              uses: appleboy/ssh-action@v1.2.2
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                script: |
                    cd EXE_BE/EXE_BE
                    git pull
                    export ASPNETCORE_ENVIRONMENT=Production
                    echo "--------------Updating Database----------------"
                    dotnet ef database update
                    echo "--------------Publishing Application----------------"
                    dotnet publish -c Release -o out
                    sudo systemctl restart exe.service
                    sleep 5
                    echo "--------------Checking Service Status----------------"
                    systemctl status exe.service
